grafana:
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  service:
    type: NodePort
    nodePort: 30300
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
alertmanager:
  enabled: true
prometheus:
  service:
    type: NodePort
    nodePort: 30900
  prometheusSpec:
    retention: 24h
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 100m
        memory: 400Mi
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: false
